### ISSUE TITLE
README Example of Pushing Messages onto Queue is Incorrect

### ISSUE THREAD

**Issue by benjaminEwhite** [iron-io/iron_mq_python#35]
[Here](https://github.com/iron-io/iron_mq_python#push-a-messages-on-the-queue):

```python
message = {
    "body" : "Test Message",
    "timeout" : 120, # Timeout, in seconds. After timeout, item will be placed back on queue. Defaults to 60.
    "delay" : 5, # The item will not be available on the queue until this many seconds have passed. Defaults to 0.
    "expires_in" : 2*24*3600 # How long, in seconds, to keep the item on the queue before it is deleted.
}
queue.post(message)
```

This won't work. You have to do a json dump of the message:

```python
import json

message = {
    "body" : "Test Message",
    "timeout" : 120, # Timeout, in seconds. After timeout, item will be placed back on queue. Defaults to 60.
    "delay" : 5, # The item will not be available on the queue until this many seconds have passed. Defaults to 0.
    "expires_in" : 2*24*3600 # How long, in seconds, to keep the item on the queue before it is deleted.
}
queue.post(json.dumps(message))
```

I lost a couple hours tracking this bug down :(

**Comment by featalion** [comment]
According to current [code](https://github.com/iron-io/iron_mq_python/blob/master/iron_mq.py#L82-L98) it must work fine, because `json.dumps()` is called internally. Which version of Python and IronMQ you are using?

**Comment by benjaminEwhite** [comment]
I'm on ironmq .5 and python 2.7.8. And actually, looking at the current code, it should *not* work fine. If you pass in a non-serialized dict, that list comprehension would produce to a list of the keys in the dict (`msg for msg in messages`)...

**Comment by featalion** [comment]
```python
def process(*messages):
  msgs = [{'body':msg} if isinstance(msg, basestring) else msg for msg in messages]
  return {'messages': msgs}

message = {
    "body" : "Test Message",
    "timeout" : 120,
    "delay" : 5,
    "expires_in" : 2*24*3600
}

print process(message)
# it prints
# {'messages': [{'body': 'Test Message', 'delay': 5, 'expires_in': 172800, 'timeout': 120}]}
```

Python 2.7.6.

**Comment by featalion** [comment]
I think, you miss, that messages parameter is prefixed with `*`, which means, that all arguments will be collected to a list.

**Comment by benjaminEwhite** [comment]
Ahhh, yes. Missed the * in process. That being said, I have a IronWorker as a subscriber to an IronMQ. If I a message post to IronMQ (in Python) without using `json.dumps`, the IW subscriber to the queue doesn't receive a task payload, but it does when I use json.dumps.

**Comment by featalion** [comment]
I am not sure, but it seems you try to use dict's fields to store your information, that you lost. All information must be stored in `body` field. It could be string or dict, which will be processed by `json.dumps` method. You will receive it as parsed dict on client side on get message if code uses `iron_mq` library. For details check [request method](https://github.com/iron-io/iron_core_python/blob/master/iron_core.py#L247-L263) of IronCore Python library.

**Comment by featalion** [comment]
Top-level dict's field are parameters of message as explained on our dev site. See "Message Object" explanation in [add message to queue](http://dev.iron.io/mq/reference/api/#add_messages_to_a_queue) API call.

**Comment by featalion** [comment]
I close this issue, because it does not exist. If you need any help, contact us through [live chat](https://hud.iron.io/users/support).
