### ISSUE TITLE
How can I install iron_mq?

### ISSUE THREAD

**Issue by Charles-lee** [iron-io/iron_mq_python#38]
I tried to install ironMQ to use it on Google App Engine(GAE).
I wish communicate some project in AppHarbor with python environment of GAE using iron_mq.

To use it I tried to install it on local machine firstly.
I have found that it need iron_core and I got the library from GitHub.
But the library need the module named 'setuptools'.
Where can I get it from?

My local machine is Windows7 and it does not have 'pip' command.

**Comment by featalion** [comment]
You can read about `setuptools` [here](https://pypi.python.org/pypi/setuptools/12.0.5).

The list of dependencies is the next:

```
|-|-> iron_mq
  |
  |-|-> iron_core
    |
    |-|-> python-dateutil
    | |-> six
    |
    |-|-> requests
      |-> pyOpenSSL
      |-> ndg-httpsclient
      |-> pyasn1
```

It would be better, if you will [install python package manager](http://stackoverflow.com/questions/4750806/how-to-install-pip-on-windows). Alternatively, you can use Linux in virtual machine.

This is not the issue of the `iron_mq` library, so, I close it. If you have more questions, please, contact support@iron.io or ask in [public support chat](https://hud.iron.io/users/support).

**Comment by Charles-lee** [comment]
Thank you very much for your answer.
