### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by pollitux** [iron-io/iron_mq_python#43]
from iron_mq import IronMQ
  File "/mnt/task/__pips__/iron_mq.py", line 1, in <module>
    import iron_core
  File "/mnt/task/__pips__/iron_core.py", line 3, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by ulandj** [comment]
Hi @pollitux,

which python stack are you using?

**Comment by ulandj** [comment]
@pollitux we have been fixed this issue: https://github.com/iron-io/iron_core_python/pull/24
Could you please try again? Only your .worker file should contain `remote` command to fetch new version of `iron_core` eg:
```
runtime 'python'
stack 'python-3.2'
pip 'iron-mq'
exec 'your_module.py'
remote
```

Thanks

**Comment by pollitux** [comment]
Thanks, specify the stack and run
