### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Koed00** [iron-io/iron_mq_python#48]
After upgrading to the latest API I get this error message:

`Version mismatch: unsupported API version '3', expected version '2', please upgrade your client. See http://docs.iron.io`

**Comment by Koed00** [comment]
Apparently  `api_version` now defaults to `3`, but setting it to `2` give 'not Found' errors.
I'll try migrating my project to v3 and see if that resolves anything

**Comment by Koed00** [comment]
I think the problem is that the `host` is routed to `mq-aws-eu-west-1.iron.io` by default and the `api` now defaults  to `3`, but that host is a v2 api. So the default host should be explicitly set to `mq-aws-eu-west-1-1.iron.io` in my case.

**Comment by ulandj** [comment]
Hi @Koed00 ,
fixed in this PR: https://github.com/iron-io/iron_core_python/pull/25

Thanks
