### ISSUE TITLE
Can't get all queues on python3.5

### ISSUE THREAD

**Issue by admiral96** [iron-io/iron_mq_python#54]
I'm using python3.5.1 and I'm getting errors when getting all queues by project.

    >>> from iron_mq import IronMQ
    >>> ironmq = IronMQ(***********)
    >>> ironmq.queues()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/mike/.pyenv/versions/dashboardenv/lib/python3.5/site-packages/iron_mq.py", line 331, in queues
        query = urllib.urlencode(options)
    AttributeError: module 'urllib' has no attribute 'urlencode'
    >>> 

I'm hitting the `ImportError` on `iron_mq.py` which is supposed to be for python2. As I investigated, I don't have the last commit even if I updated `iron-mq` dependency

**Comment by admiral96** [comment]
As I investigated, I don't have the last commit even if I updated `iron-mq` dependency

**Comment by jeicoo** [comment]
@admiral96 , I am getting the same error right now, have you resolved this issue?

**Comment by admiral96** [comment]
@jeicoo I haven't resolve this yet. While waiting for updates on pypi, my current workaround is to step-down python-version(2.7).

**Comment by jeicoo** [comment]
Thank you @admiral96 ! I observed that they already have a fix for this issue, I resolved my issue by just downloading the `iron_mq.py` manually and include it in my script.
